"""Explicit Jev aliases for every group in the bundled CCCC directory.

Keys use the Agenda's ``group_key`` normalization. Values keep their readable spelling;
the canonical name is sent separately. Alongside documented nicknames and distinctive
short names, full descriptive forms ("Colla Castellera de…") cover groups without a
known nickname. Never use a bare place name or invent an acronym from initials.

Sources, checked 2026-09-24:
https://castellscat.cat/public/ca/les-colles-llistat
https://barometrecasteller.cat/noms-sobrenoms-i-malnoms-de-les-colles-actuals/
https://www.cerdanyola.cat/guia/entitat/entitats-de-cultura/castellers-de-cerdanyola-martinets
https://www.elsgrocs.cat/instanova/ae4rtfj76lo/web/
https://exteriors.gencat.cat/ca/ambits-dactuacio/afers_exteriors/catalunya-exterior/actualitat/250731_Cardats-10-anys

Changes affect classification: bump CRITERIA_VERSION in jev.py with this catalogue.
"""

GROUP_ALIASES: dict[str, list[str]] = {
    "al·lots de llevant": ["Al·lots", "Colla dels Al·lots de Llevant"],
    "bordegassos de vilanova": ["Bordegassos", "Bordegassos de Vilanova i la Geltrú"],
    "brivalls de cornudella": ["Brivalls", "Brivalls de Cornudella de Montsant"],
    "capgrossos de mataro": ["Capgrossos", "Colla dels Capgrossos de Mataró"],
    "castellers d'altafulla": ["Colla Castellera d'Altafulla"],
    "castellers d'andorra": ["Colla Castellera d'Andorra"],
    "castellers d'esparreguera": ["Colla Castellera d'Esparreguera"],
    "castellers d'esplugues": ["Cargolins", "Castellers d'Esplugues de Llobregat"],
    "castellers de badalona": ["Micacos", "Colla Castellera de Badalona"],
    "castellers de barcelona": ["Colla dels Castellers de Barcelona"],
    "castellers de berga": ["Colla Castellera de Berga"],
    "castellers de caldes de montbui": ["Escaldats", "Castellers de Caldes"],
    "castellers de castellar del valles": ["Capgirats", "Castellers de Castellar"],
    "castellers de castelldefels": ["Els Grocs", "Colla Castellera de Castelldefels"],
    "castellers de cerdanyola": ["Martinets", "Castellers de Cerdanyola del Vallès"],
    "castellers de cornella": ["Castellers de Cornellà de Llobregat"],
    "castellers de l'adroc": ["Colla Castellera de l'Adroc"],
    "castellers de la sagrada familia": [
        "Castellers de Sagrada Família",
        "Colla de la Sagrada Família",
    ],
    "castellers de la selva": ["Guillats", "Colla Castellera de la Selva"],
    "castellers de la vila de gracia": ["Castellers de Gràcia", "Colla de la Vila de Gràcia"],
    "castellers de les roquetes": ["Colla Castellera de les Roquetes"],
    "castellers de lleida": ["Colla Castellera de Lleida"],
    "castellers de mallorca": ["Colla dels Castellers de Mallorca"],
    "castellers de mediona": ["Colla Castellera de Mediona"],
    "castellers de mollet": ["Castellers de Mollet del Vallès"],
    "castellers de montcada i reixac": ["Castellers de Montcada"],
    "castellers de rubi": ["Colla Castellera de Rubí"],
    "castellers de sabadell": ["Saballuts", "Colla Castellera de Sabadell"],
    "castellers de sant adria": ["Passadors", "Castellers de Sant Adrià de Besòs"],
    "castellers de sant cugat": ["Gausacs", "Castellers de Sant Cugat del Vallès"],
    "castellers de sant feliu": ["Magentes", "Castellers de Sant Feliu de Llobregat"],
    "castellers de sant vicenc dels horts": [
        "Carallots",
        "Colla Castellera de Sant Vicenç dels Horts",
    ],
    "castellers de santa coloma": ["Castellers de Santa Coloma de Gramenet"],
    "castellers de santpedor": ["Colla Castellera de Santpedor"],
    "castellers de sants": ["Borinots", "Colla dels Castellers de Sants"],
    "castellers de sarria": ["Colla Castellera de Sarrià"],
    "castellers de terrassa": ["Colla dels Castellers de Terrassa"],
    "castellers de tortosa": ["Colla Castellera de Tortosa"],
    "castellers de viladecans": ["Colla Castellera de Viladecans"],
    "castellers de vilafranca": ["Verds", "Castellers de Vilafranca del Penedès"],
    "castellers del baix montseny": ["Colla Castellera del Baix Montseny"],
    "castellers del foix de cubelles": ["Castellers del Foix", "Colla dels Castellers de Cubelles"],
    "castellers del llucanes": ["Cabirols", "Colla Castellera del Lluçanès"],
    "castellers del pallars": ["Malfargats", "Colla Castellera del Pallars"],
    "castellers del poble sec": ["Bandarres", "Castellers del Poble-sec"],
    "castellers del prat de llobregat": ["Castellers del Prat", "Colla Castellera del Prat"],
    "castellers del riberal": ["Colla Castellera del Riberal"],
    "colla castellera d'edinburgh": [
        "Cardats",
        "Cardats d'Edinburgh",
        "Castellers d'Edinburgh",
        "Castellers d'Edimburg",
    ],
    "colla castellera de berlin": ["Castellers de Berlín"],
    "colla castellera de cerdanya": ["Castellers de Cerdanya", "Colla Castellera de la Cerdanya"],
    "colla castellera de figueres": ["Merlots", "Castellers de Figueres"],
    "colla castellera de gava": ["Castellers de Gavà"],
    "colla castellera de l'alt maresme i la selva maritima": [
        "Maduixots",
        "Castellers de l'Alt Maresme",
        "Colla Castellera de l'Alt Maresme",
        "Castellers de l'Alt Maresme i la Selva Marítima",
    ],
    "colla castellera de l'esquerra de l'eixample": [
        "Esquerdats",
        "Castellers de l'Esquerra de l'Eixample",
    ],
    "colla castellera de madrid": ["Gatos", "Castellers de Madrid"],
    "colla castellera de vacarisses": ["Potes Roges", "Castellers de Vacarisses"],
    "colla castellera els encantats de begues": ["Encantats", "Encantats de Begues"],
    "colla castellera jove de barcelona": ["Jove de Barcelona", "Colla Jove de Barcelona"],
    "colla castellera la bisbal del penedes": [
        "Bous",
        "Bous de la Bisbal",
        "Castellers de la Bisbal del Penedès",
        "Colla Castellera de la Bisbal del Penedès",
    ],
    "colla castellera sant pere i sant pau": [
        "Castellers de Sant Pere i Sant Pau",
        "Colla Castellera de Sant Pere i Sant Pau",
    ],
    "colla jove de castellers de sitges": ["Jove de Sitges", "Colla Jove de Sitges"],
    "colla jove de l'hospitalet": [
        "Jove de l'Hospitalet",
        "Colla Jove de l'Hospitalet de Llobregat",
    ],
    "colla jove xiquets de tarragona": [
        "Jove de Tarragona",
        "Jove Xiquets de Tarragona",
        "Colla Jove de Tarragona",
    ],
    "colla joves xiquets de valls": [
        "Colla Joves",
        "Joves de Valls",
        "La Joves",
        "Diables Vermells",
    ],
    "colla vella dels xiquets de valls": [
        "Colla Vella",
        "Vella de Valls",
        "La Vella",
        "Rosats",
        "Colla Vella Xiquets de Valls",
    ],
    "esperxats de l'estany": ["Esperxats", "Esperxats del Pla de l'Estany"],
    "laietans de gramenet": ["Laietans", "Laietans i Laietanes de Gramenet"],
    "manyacs de parets": ["Manyacs", "Manyacs de Parets del Vallès"],
    "margeners de guissona": ["Margeners", "Colla dels Margeners de Guissona"],
    "marrecs de salt": ["Marrecs", "Colla dels Marrecs de Salt"],
    "matossers de molins de rei": ["Matossers", "Colla dels Matossers de Molins de Rei"],
    "minyons de l'arboc": ["Colla dels Minyons de l'Arboç"],
    "minyons de santa cristina d'aro": ["Minyons de Santa Cristina"],
    "minyons de terrassa": ["Minyons", "Malves", "Colla dels Minyons de Terrassa"],
    "moixiganguers d'igualada": ["Moixiganguers", "Colla dels Moixiganguers d'Igualada"],
    "nens del vendrell": ["Nens", "Colla dels Nens del Vendrell"],
    "nois de la torre": ["Nois de Torredembarra", "Colla dels Nois de la Torre"],
    "pallagos del conflent": ["Pallagos", "Colla dels Pallagos del Conflent"],
    "sagals d'osona": ["Sagals", "Colla dels Sagals d'Osona"],
    "salats de suria": ["Salats", "Colla dels Salats de Súria"],
    "tirallongues de manresa": ["Tirallongues", "Esquimals"],
    "torraires de montblanc": ["Torraires", "Colla dels Torraires de Montblanc"],
    "vailets de gelida": ["Colla dels Vailets de Gelida"],
    "xerrics d'olot": ["Xerrics", "Colla dels Xerrics d'Olot"],
    "xicots de vilafranca": ["Xicots", "Xicotes i Xicots de Vilafranca"],
    "xics de granollers": ["Xics", "Colla dels Xics de Granollers"],
    "xiquelos i xiqueles del delta": ["Xiqüelos del Delta", "Xiqüeles del Delta"],
    "xiquets de cambrils": ["Colla dels Xiquets de Cambrils"],
    "xiquets de reus": ["Colla dels Xiquets de Reus"],
    "xiquets de tarragona": ["Matalassers", "Colla dels Xiquets de Tarragona"],
    "xiquets de vila-seca": ["Xiquets de Vilaseca", "Colla dels Xiquets de Vila-seca"],
    "xiquets del serrallo": ["Colla dels Xiquets del Serrallo"],
    # University groups: keep their distinctive name, never the university acronym alone.
    "arreplegats de la zona universitaria": ["Arreplegats"],
    "bergants del campus de terrassa": ["Bergants", "Bergants de Terrassa"],
    "descargolats de l'eebe": ["Descargolats"],
    "emboirats de la universitat de vic": ["Emboirats", "Emboirats de la UVic"],
    "engrescats de la url": ["Engrescats", "Engrescats de la Universitat Ramon Llull"],
    "gambirots de la uib": ["Gambirots", "Gambirots de la Universitat de les Illes Balears"],
    "ganapies de la uab": ["Ganàpies", "Ganàpies de la Universitat Autònoma de Barcelona"],
    "grillats del campus del baix llobregat": ["Grillats", "Grillats del Baix Llobregat"],
    "llunatics upc vilanova": ["Llunàtics", "Llunàtics de la UPC de Vilanova"],
    "passerells del tcm": ["Passerells", "Passerells del TecnoCampus"],
    "pataquers de la urv": ["Pataquers", "Pataquers de la Universitat Rovira i Virgili"],
    "penjats del campus de manresa": ["Penjats", "Penjats de Manresa"],
    "trempats de la upf": ["Trempats", "Trempats de la Universitat Pompeu Fabra"],
    "xoriguers de la udg": ["Xoriguers", "Xoriguers de la Universitat de Girona"],
    # International groups: explicit translated/spelling variants retain the group term.
    "castellers d'estocolm": ["Castellers de Stockholm", "Colla Castellera d'Estocolm"],
    "castellers d'eire": ["Castellers d'Irlanda", "Colla Castellera d'Éire"],
    "castellers de boston": ["Colla Castellera de Boston"],
    "castellers de lausanne": ["Castellers de Lausana", "Colla Castellera de Lausanne"],
    "castellers de lo prado": ["Colla Castellera de Lo Prado"],
    "castellers de montreal": ["Colla Castellera de Montreal"],
    "castellers de paris": ["Geperuts", "Colla Castellera de París"],
    "castellers de sydney": ["Colla Castellera de Sydney"],
    "castellers de zurich": ["Castellers de Zuric", "Colla Castellera de Zürich"],
    "castellers of london": ["Castellers de Londres", "London Castellers"],
    "mannekes de brussel·les": ["Mannekes", "Castellers de Brussel·les"],
    "xiquets de copenhagen": ["Xiquets de Copenhaguen", "Xiquets de Copenhague"],
}
